# Generated by Django 2.2.2 on 2019-06-08 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20190608_1737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='answers',
        ),
        migrations.AddField(
            model_name='question',
            name='hint',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Hint'),
        ),
        migrations.AddField(
            model_name='question',
            name='negative_answer1',
            field=models.TextField(default=100),
        ),
        migrations.AddField(
            model_name='question',
            name='negative_answer2',
            field=models.TextField(default=100),
        ),
        migrations.AddField(
            model_name='question',
            name='positive_answer',
            field=models.TextField(default=100),
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
