# Generated by Django 2.2.2 on 2019-06-08 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20190608_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='negative_answer1',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='negative_answer2',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='positive_answer',
            field=models.TextField(),
        ),
    ]
