# Generated by Django 2.2.2 on 2019-06-08 18:18

from django.db import migrations, models
import tagging.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20190608_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hint',
            name='content',
            field=models.TextField(verbose_name='Zawartosć'),
        ),
        migrations.AlterField(
            model_name='hint',
            name='publish_date',
            field=models.DateTimeField(verbose_name='Data publikacji'),
        ),
        migrations.AlterField(
            model_name='hint',
            name='tags',
            field=tagging.fields.TagField(blank=True, max_length=255, verbose_name='Tagi'),
        ),
        migrations.AlterField(
            model_name='hint',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Tytuł'),
        ),
    ]
