# Generated by Django 2.2.2 on 2019-06-08 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20190608_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='hint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Hint'),
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='question',
        ),
        migrations.AddField(
            model_name='quiz',
            name='question',
            field=models.ManyToManyField(to='core.Question'),
        ),
    ]
