# Generated by Django 2.2.2 on 2019-06-08 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20190608_1905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='hint',
        ),
        migrations.AddField(
            model_name='hint',
            name='quiz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Quiz'),
        ),
    ]
