# Generated by Django 2.2.2 on 2019-06-08 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20190608_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='title',
            field=models.TextField(null=True),
        ),
    ]
