# Generated by Django 2.2.2 on 2019-06-08 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_quiz_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='hint',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Hint'),
        ),
    ]
