# Generated by Django 2.2.2 on 2019-06-08 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20190608_1958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hint',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='question',
            name='hint',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='title',
        ),
        migrations.AddField(
            model_name='quiz',
            name='hint',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Hint'),
        ),
    ]
