# Generated by Django 2.2.2 on 2019-06-08 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20190608_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='hint',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Hint'),
        ),
    ]
