# Generated by Django 2.2.2 on 2019-06-09 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20190608_2014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='hint',
        ),
        migrations.AddField(
            model_name='hint',
            name='quiz',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='title', to='core.Quiz'),
        ),
        migrations.AlterField(
            model_name='question',
            name='hint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Hint', verbose_name='Porada'),
        ),
    ]
