# Generated by Django 2.2.2 on 2019-06-09 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_quiz_for_hint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hint',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='for_hint',
        ),
        migrations.AddField(
            model_name='quiz',
            name='hint',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='core.Hint'),
        ),
    ]
