# Generated by Django 2.2.2 on 2019-06-09 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20190609_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='for_hint',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='hint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='core.Hint'),
        ),
    ]
