# Generated by Django 2.2.2 on 2019-06-09 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20190609_1232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='for_hint',
        ),
    ]
