# Generated by Django 2.2.2 on 2019-06-09 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_auto_20190609_1550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='question',
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Quiz'),
        ),
    ]
