# Generated by Django 2.2.2 on 2019-06-09 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_auto_20190609_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='quiz',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question', to='core.Quiz'),
        ),
    ]
