# Generated by Django 2.2.2 on 2019-06-09 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_auto_20190609_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='hint',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='core.Hint'),
        ),
    ]
