# Generated by Django 2.2.2 on 2019-06-09 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_auto_20190609_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hint',
            name='publish_date',
            field=models.DateTimeField(null=True, verbose_name='Data publikacji'),
        ),
    ]
