# Generated by Django 2.2.2 on 2019-06-08 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hint',
            options={'ordering': ('publish_date',)},
        ),
    ]
